### ISSUE TITLE
Branch names

### ISSUE THREAD

**Issue by lgatto** [rformassspectrometry/MsCoreUtils#113]
I just pushed a fix and have seen that the main branch was names `devel`. I understand that this has been done to match the new branch names on the Bioconductor git server, but I don't like it and there's no reason to match the branch names - Github and git.bioconductor.org are independent remotes. 

Bioconductor has its reason to call it branches `devel`, `RELEASE_3_16`, ... and Github and git have their own way: `master` originally and now `main`. Wanting to match these is in my opinion confusing for everybody but Bioconductor developers. 

I would very much prefer to revert back on Github.

cc @jorainer @sgibb

**Comment by jorainer** [comment]
IMHO Bioconductor's naming scheme make sense, because the *main* branch we usually have is in fact a developmental branch usually depending on other (devel) packages. Also, it reduces a bit the overhead pushing and merging changes to/from Bioconductor. And this was also a good opportunity to move/rename all the old *master* branches to something new.

But I'm OK to revert if you like. And sorry that I caused this confusion - I was not aware that you are against renaming the branches.
