### ISSUE TITLE
matching: y/table, tolerance and/or ppm argument

### ISSUE THREAD

**Issue by sgibb** [rformassspectrometry/MsCoreUtils#12]
Currently we have three matching functions with the following definitions:
https://github.com/rformassspectrometry/MsCoreUtils/blob/09969f8865581d50b8b7e5f1d3323f75fa2bc107/R/matching.R#L89-L91
https://github.com/rformassspectrometry/MsCoreUtils/blob/09969f8865581d50b8b7e5f1d3323f75fa2bc107/R/matching.R#L156-L157
https://github.com/rformassspectrometry/MsCoreUtils/blob/09969f8865581d50b8b7e5f1d3323f75fa2bc107/R/matching.R#L213-L214

To make the interface of these functions as similar as possible I am wondering whether we should
1. Rename `y` in `join` to `table`? 
I would like to keep it as currently implemented because `closest`/`common` are similar to `match`/`%in%` where the second argument is called `table`. On the other hand `join` combines two `numeric`s without any of the being superior/special to the other so I think `x` and `y` are useful names here.
2. Add `ppm` to `closest` and `common` or remove `ppm` from `join`? 
I tend to remove the `ppm` argument from `join` because I found two different tolerance arguments (`tolerance` and `ppm`) slightly confusing. But it would be somehow problematic because the user has to known that `ppm(x, ppm)` (**x**) is needed for `join(x, y, type = c("outer", "right", "inner"))` but `ppm(y, ppm)` (**y**) for `join(x, y, type = "left")`. If we decide to remove `ppm` I am going to change this in a way that the user can always call `join(x, y, tolerance = tolerance + ppm(x, ppm))`. 

@lgatto, @jorainer What is your opinion?

**Comment by jorainer** [comment]
I agree on 1) to keep `y` and not rename that to `table`.

Regarding 2): I would like to keep the `ppm` argument here. In the upper level function I will also want to have a `tolerance` **and** `ppm` parameter because I think that's much easier for the end user to understand (`tolerance` is a constant difference, `ppm` a values-relative difference). Also, the way how `ppm` is included into `tolerance` seems to be an ideal source for bugs and misimplementations (especially the difference for the left/right join you mention) - and fixing that inside `join` could result in a slightly lower performance - only to remove a usefull parameter? 

So, I vote for keeping everything the way you have implemented it.

**Comment by sgibb** [comment]
Am 31. Juli 2019 07:40:42 MESZ schrieb Johannes Rainer <notifications@github.com>:
>I agree on 1) to keep `y` and not rename that to `table`.
>
>Regarding 2): I would like to keep the `ppm` argument here. In the
>upper level function I will also want to have a `tolerance` **and**
>`ppm` parameter because I think that's much easier for the end user to
>understand (`tolerance` is a constant difference, `ppm` a
>values-relative difference). Also, the way how `ppm` is included into
>`tolerance` seems to be an ideal source for bugs and misimplementations
>(especially the difference for the left/right join you mention) - and
>fixing that inside `join` could result in a slightly lower performance
>- only to remove a usefull parameter? 
>
>So, I vote for keeping everything the way you have implemented it.

We could add `ppm` to `closest`/`common` as well?

**Comment by jorainer** [comment]
Well - why not?
