### ISSUE TITLE
MsCoreUtils documentation topics

### ISSUE THREAD

**Issue by lgatto** [rformassspectrometry/MsCoreUtils#8]
`MsCoreUtils` is going to grow very quickly to a point where it will be difficult to remember what is available. To help to keep track and find things, I would suggest we define a set to manual page topics (with `\alias{topic}`) and concepts (with `\concept{an important concept}`) to be able to navigate the man pages more efficiently.

**Comment by sgibb** [comment]
I never used `\concept` before but that should be no problem. I am not sure which *alias* we should set (because additional names for functions won't be useful so it have to be some kind of short sentence).
I tried setting a topic with `@aliases` in roxygen (`@aliases Finding Extreme Value`) but while 
[Writing R Extensions](https://cran.r-project.org/doc/manuals/R-exts.html#Documenting-functions) says
> The \alias sections specify all “topics” the file documents. This information is collected into index data bases for lookup by the on-line (plain text and HTML) help systems. The topic can contain spaces, but (for historical reasons) leading and trailing spaces will be stripped. Percent and left brace need to be escaped by a backslash. 

`roxygen` doesn't allow spaces in topic (because they are interpreted as new aliases).
I tried the following things (and google didn't really helped):
```r
#' @aliases Finding Extreme Values # \alias{Finding}, \alias{Extreme}, \alias{Values}
#' @aliases "Finding Extreme Values" # \alias{"Finding}, \alias{Extreme}, \alias{Values"}
#' @aliases Finding\\ Extreme\\ Values # \alias{Finding\}, \alias{Extreme\}, \alias{Values}
```

(BTW: adding `\alias{Finding Extreme Values}` to the Rd files works without any problems)

So if we really want to do that I am going to report a bug in `roxygen2`.

**Comment by sgibb** [comment]
I remember that Rd is more or less LaTeX so I tried `#' @aliases Finding~Extreme~Values` and that works.

**Comment by lgatto** [comment]
What I would like to achieve is something like the [`ggplot2` reference page](https://ggplot2.tidyverse.org/reference/index.html), on the right. I now realise that this is managed manually in the [`_pkgdown.yml](https://github.com/tidyverse/ggplot2/blob/master/_pkgdown.yml) file. 

What are the effects of concepts on the pkgdown page? Any at all?

**Comment by sgibb** [comment]
I added the new [_pkgdown.yml](https://github.com/rformassspectrometry/MsCoreUtils/blob/master/pkgdown/_pkgdown.yml) file:
https://github.com/rformassspectrometry/MsCoreUtils/blob/79e4c235e594bf31363e8af7018d0e358e34b2e7/pkgdown/_pkgdown.yml#L1-L13

Please feel free to modify everything and reopen this issue.

`@family description of similar functions` adds `\concept{description of similar functions}` (not visible on pkgdown) and `\seealso{Other description of similar functions: (list of functions with the same family string}` (also added to pkgdown).
