### ISSUE TITLE
Feature request: add random forest imputation

### ISSUE THREAD

**Issue by cvanderaa** [rformassspectrometry/MsCoreUtils#82]
Hi, 
I've received feedback from a user that is using `scp` which depends on `QFeatures`. The user asked whether we could also implement a random forest imputation. He suggested the `missForest` package. Taking advantage of the wrapper function that already exists in `imp4p` (the function is called `impute.RF`) might facilitate its integration in the `rformassspectrometry` project. I thought that this could fit in the `MsCoreUtils` package.

**Comment by jorainer** [comment]
My only concern is that we should try to keep the dependencies of the `MsCoreUtils` package as small as possible - also to reduce package loading time.

**Comment by lgatto** [comment]
Yes, I agree that we should avoid too many dependencies.

- We would have these as suggests (which is already the case for many dependencies related to imputation and normalisation). Would that be ok, not only for now, but as a general solution for future situations.
- Otherwise, we could externalise some of the `MsCoreUtils` function, say all the imputation ones, to a dedicated package. Not sure this would be the best option at this stage though.

**Comment by jorainer** [comment]
`Suggests` with `requireNamespace` is fine for me

**Comment by cvanderaa** [comment]
This issue is solved by PR #98
